name: Build Docker Image and Deploy to Test

on: workflow_dispatch

jobs:
  build-docker-image:
    runs-on: self-hosted
    steps:
      - name: Checkout API
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: blog-rest-api/.
          file: ./blog-rest-api/Dockerfile
          push: true
          tags: ghcr.io/bundulappp/blog-rest-api:latest
